// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4leezbbQpAXQYvF1_E6ZzE1ftKqErPA',
    appId: '1:1053308876013:web:6da806687246c8ec52c8e4',
    messagingSenderId: '1053308876013',
    projectId: 'attendx-8b4c5',
    authDomain: 'attendx-8b4c5.firebaseapp.com',
    storageBucket: 'attendx-8b4c5.firebasestorage.app',
    measurementId: 'G-M2FV0YME7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopavg5KfH1D6CPxK31SjmbIfhTF7d_dI',
    appId: '1:1053308876013:android:5cb12ca53fb9fffc52c8e4',
    messagingSenderId: '1053308876013',
    projectId: 'attendx-8b4c5',
    storageBucket: 'attendx-8b4c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdT4VGqBgREfBNka4Qhm34H2HVBSSe2VE',
    appId: '1:1053308876013:ios:3e0ac0f2ad56ca8c52c8e4',
    messagingSenderId: '1053308876013',
    projectId: 'attendx-8b4c5',
    storageBucket: 'attendx-8b4c5.firebasestorage.app',
    iosClientId: '1053308876013-49hmghh2119ags5kjasksemsoc8m6i3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdT4VGqBgREfBNka4Qhm34H2HVBSSe2VE',
    appId: '1:1053308876013:ios:3e0ac0f2ad56ca8c52c8e4',
    messagingSenderId: '1053308876013',
    projectId: 'attendx-8b4c5',
    storageBucket: 'attendx-8b4c5.firebasestorage.app',
    iosClientId: '1053308876013-49hmghh2119ags5kjasksemsoc8m6i3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4leezbbQpAXQYvF1_E6ZzE1ftKqErPA',
    appId: '1:1053308876013:web:90f655c0aa25401d52c8e4',
    messagingSenderId: '1053308876013',
    projectId: 'attendx-8b4c5',
    authDomain: 'attendx-8b4c5.firebaseapp.com',
    storageBucket: 'attendx-8b4c5.firebasestorage.app',
    measurementId: 'G-H1CBG5R573',
  );
}
